[tool.poetry]
name = "adaswarm"
version = "0.1.0"
description = ""
authors = ["swhustla <fdkelly@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.10.0"
torchvision = "^0.11.1"
tensorboard = "^2.7.0"
torch-tb-profiler = "^0.3.1"
pandas = "^1.4.0"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
black = "^21.12b0"
py-spy = "^0.3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
