name: GitHub Actions Demo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Check out repository code
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'

        - name: Install dependencies 
          run: |
            python -m venv ./venv
            source ./venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
          shell: bash

        - name: Lint and verify python code
          run: |
            pylint -d duplicate-code examples/main.py adaswarm/particle.py
          shell: bash

        - name: Run unit tests
          run: |
            python -m unittest tests/unit/test*
          shell: bash
