name: GitHub Actions Demo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Check out repository code
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - uses: Gr1N/setup-poetry@v7

        - name: Install dependencies 
          run: |
            poetry install
          shell: bash

        - name: Lint and verify python code
          run: |
            poetry run pylint -d duplicate-code examples/main.py
          shell: bash

        - name: Run unit tests
          run: |
            poetry run python -m unittest tests/unit/*
          shell: bash
